# logger options
snapshot_save_iter: 10000    # How often do you want to save trained models
image_save_iter: 1
log_iter: 1                 # How often do you want to log the training stats
test_iter: 10000

# optimization options
max_iter: 1000000             # maximum number of training iterations
batch_size: 2                 # batch size
weight_decay: 0.0001          # weight decay
beta1: 0.5                    # Adam parameter
beta2: 0.999                  # Adam parameter
init: orthogonal                 # initialization [gaussian/kaiming/xavier/orthogonal]
lr: 0.001                     # initial learning rate
lr_decay: 0.00001             # initial learning rate
lr_policy: step               # learning rate scheduler
step_size: 10000              # how often to decay learning rate
gamma: 0.5                    # how much to decay learning rate
content_weight: 1                # loss weight
style_weight: 1                  # loss weight
mrf_weight: 0                    # loss weight


# model options

vgg: models/vgg_normalised.pth
rp_blocks: 5
in_dim: 3
hidden_dim : 32
ld_layer_num: 5
inception_num: 0          # 1 * 1 Conv
enc_stack_way: 'NONE'
k: 5
fusion_block: 5
network: ld_adain4
spade_block: 5
spade: true
spade_norm: instance
ndf: 2
stylized_layers: 5


# segmentation options

class_num: 19



# data options
num_workers: 8                                            # number of data loading threads
img_size: 512
# content_dir: /data/jsy/datasets/COCO2017/train2017
# style_dir: /data/jsy/datasets/wikiart/wikiart
content_dir: /home/jsy/datasets/train2017
style_dir: /home/jsy/datasets/wikiart

test_dir: /data/lxd/datasets/photo_data
seg_dir: /data/lxd/datasets/photo_data/segmentation
checkpoint_path: output/0119_MultiAdaINRPNet_rp5_incep0_lr1e-4_hiddim64_cw1_sw1/checkpoints/55000.pth
output: output/0131_ld3_lr-4_hiddim32_s5
resume: False
use_mask: True



# dataset options 
test_dataset: 'photoreal'